# Dockerfile
# A dockerfile for development

FROM elixir:alpine

RUN mkdir -p /opt/app

COPY . /opt/app
WORKDIR /opt/app

RUN apk --no-cache --update add \
  bash git make g++ inotify-tools \
  nodejs nodejs-npm python && \
  npm install npm -g --no-progress

RUN cd /opt/app && \
  mix local.hex --force && \
  mix local.rebar --force && \
  mix deps.get --all && \
  MIX_ENV=dev mix deps.compile --all && \
  MIX_ENV=test mix deps.compile --all && \
  cd /opt/app/assets && \
  npm ci

EXPOSE 4000

ENTRYPOINT ["mix"]
CMD ["phx.server"]
